# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('join_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('work', models.CharField(max_length=10, null=True)),
                ('personal_profile', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
    ]
